const fname = document.getElementById('fname')
const lname = document.getElementById('lname')
const email = document.getElementById('email')
const pass = document.getElementById('pass')
const form = document.getElementById('form')